/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author Wavin
 */
public class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */
    
    CasillaCalle tituloPropiedad;
    
    public PropiedadPanel() {
        initComponents();
    }
    
    public void setPropiedad(CasillaCalle propiedad){
        this.tituloPropiedad = propiedad;
        this.nombrePropiedad.setText(this.tituloPropiedad.getNombre());
        Integer numCasas = this.tituloPropiedad.getNumCasas();
        Integer numHoteles = this.tituloPropiedad.getNumHoteles();
        this.numCasas.setText(numCasas.toString());
        this.numHoteles.setText(numHoteles.toString());
        
        
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombrePropiedad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numCasas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numHoteles = new javax.swing.JTextField();

        jLabel1.setText("Nombre Titulo Propiedad");
        add(jLabel1);

        nombrePropiedad.setEditable(false);
        nombrePropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePropiedadActionPerformed(evt);
            }
        });
        add(nombrePropiedad);

        jLabel2.setText("Numero de Casas");
        add(jLabel2);

        numCasas.setEditable(false);
        numCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCasasActionPerformed(evt);
            }
        });
        add(numCasas);

        jLabel3.setText("Numero de Hoteles");
        add(jLabel3);

        numHoteles.setEditable(false);
        numHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numHotelesActionPerformed(evt);
            }
        });
        add(numHoteles);
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePropiedadActionPerformed

    private void numCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCasasActionPerformed

    private void numHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numHotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numHotelesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombrePropiedad;
    private javax.swing.JTextField numCasas;
    private javax.swing.JTextField numHoteles;
    // End of variables declaration//GEN-END:variables
}
